game.resources = [
	// Graphics: {name: "example", type:"image", src: "data/img/example.png"},
	{name: "eggy", type:"image", src: "data/img/sprite/eggy.png"},
	// area01
    {name: "refridge_level_background", type:"image", src: "data/img/backgrounds/refridge_level_background.png"},
	{name: "carton", type:"image", src: "data/img/sprite/area01/carton.png"},
	{name: "refridge_dark", type:"image", src: "data/img/sprite/area01/refridge_dark.png"},
	{name: "door2", type:"image", src: "data/img/sprite/area01/door2.png"},
	{name: "sausage_rope", type:"image", src: "data/img/sprite/area01/sausage_rope.png"},
	{name: "sausage_se", type:"image", src: "data/img/sprite/area01/sausage_se.png"},
	{name: "chicken_leg", type:"image", src: "data/img/sprite/area01/chicken_leg.png"},
	{name: "cheese", type:"image", src: "data/img/sprite/area01/cheese.png"},
	{name: "icicle", type:"image", src: "data/img/sprite/area01/icicle.png"},
	{name: "snowflakes", type:"image", src: "data/img/sprite/area01/snowflake.png"},
    {name: "icecream_pouring", type:"image", src: "data/img/sprite/area01/icecream_pouring.png"},
    {name: "fridge_obj4", type:"image", src: "data/img/sprite/area01/fridge_obj4.png"},
    {name: "breakingPlatform", type:"image", src: "data/img/sprite/area01/refridge_obj1.png"},
    {name: "mouse", type:"image", src: "data/img/sprite/area01/mouse.png"},
    {name: "juice", type:"image", src: "data/img/sprite/area01/juice.png"},
    {name: "soda", type:"image", src: "data/img/sprite/area01/soda.png"},
    //area02
    {name: "shelf_level_foreground", type:"image", src: "data/img/backgrounds/shelf_level_foreground.png"},
    {name: "shelf_level_background", type:"image", src: "data/img/backgrounds/shelf_level_background.png"},
    {name: "books", type:"image", src: "data/img/sprite/area02/books.png"},
	{name: "applecider", type:"image", src: "data/img/sprite/area02/applecider.png"},
	{name: "pouringcider", type:"image", src: "data/img/sprite/area02/pouringcider.png"},
	{name: "mallet_movement", type:"image", src: "data/img/sprite/area02/mallet_movement.png"},
	{name: "paper_towel", type:"image", src: "data/img/sprite/area02/paper_towel.png"},
	{name: "shelf", type:"image", src: "data/img/sprite/area02/shelf.png"},
	{name: "break_pipe", type:"image", src: "data/img/sprite/area02/break_pipe.png"},
	{name: "clock", type:"image", src: "data/img/sprite/area02/clock.png"},
	{name: "coffee_pot", type:"image", src: "data/img/sprite/area02/coffee_pot.png"},
	{name: "blue", type:"image", src: "data/img/sprite/area02/blue.png"},
	{name: "salt", type:"image", src: "data/img/sprite/area02/salt.png"},
	{name: "ketchup_mustard", type:"image", src: "data/img/sprite/area02/ketchup_mustard.png"},
	{name: "salt_pepper", type:"image", src: "data/img/sprite/area02/salt_pepper.png"},
	{name: "oil2", type:"image", src: "data/img/sprite/area02/oil2.png"},
	{name: "coffee_mix", type:"image", src: "data/img/sprite/area02/coffee_mix.png"},
	{name: "light", type:"image", src: "data/img/sprite/area02/light.png"},
	{name: "candy", type:"image", src: "data/img/sprite/area02/candy.png"},
	{name: "key_flying", type:"image", src: "data/img/sprite/area02/key_flying.png"},
	//area03
	{name: "level_3_background", type:"image", src: "data/img/backgrounds/level_3_background.png"},
	{name: "level_3_transparent", type:"image", src: "data/img/backgrounds/level_3_transparent.png"},
    {name: "pipe", type:"image", src: "data/img/sprite/area03/pipe.png"},
	{name: "button1", type:"image", src: "data/img/sprite/area03/button1.png"},
	{name: "water_animation2", type:"image", src: "data/img/sprite/area03/water_animation2.png"},
	{name: "water_animation3", type:"image", src: "data/img/sprite/area03/water_animation3.png"},
	{name: "water_switch", type:"image", src: "data/img/sprite/area03/water_switch.png"},
	{name: "tank_a", type:"image", src: "data/img/sprite/area03/tank_a.png"},
	{name: "tank_b", type:"image", src: "data/img/sprite/area03/tank_b.png"},
	{name: "rat2", type:"image", src: "data/img/sprite/area03/rat2.png"},
	{name: "spider", type:"image", src: "data/img/sprite/area03/spider.png"},
	//area04
	{name: "level4_background_yi", type:"image", src: "data/img/backgrounds/level4_background_yi.png"},
	{name: "sponge", type:"image", src: "data/img/sprite/area04/sponge.png"},
	{name: "sinkLid", type:"image", src: "data/img/sprite/area04/sinkLid.png"},
	{name: "counterdoor_left", type:"image", src: "data/img/sprite/area04/counterdoor_left.png"},
	{name: "counterdoor_right", type:"image", src: "data/img/sprite/area04/counterdoor_right.png"},
	{name: "faucet_water", type:"image", src: "data/img/sprite/area04/faucet_water.png"},
	{name: "fauset_switch", type:"image", src: "data/img/sprite/area04/fauset_switch.png"},
	{name: "faucet_turning", type:"image", src: "data/img/sprite/area04/faucet_turning.png"},
	{name: "counter_front", type:"image", src: "data/img/sprite/area04/counter_front.png"},
	{name: "stove_switch", type:"image", src: "data/img/sprite/area04/stove_switch.png"},
	{name: "container_door", type:"image", src: "data/img/sprite/area04/container_door.png"},
	{name: "container", type:"image", src: "data/img/sprite/area04/container.png"},
	{name: "curtain", type:"image", src: "data/img/sprite/area04/curtain.png"},
	{name: "fire", type:"image", src: "data/img/sprite/area04/fire.png"},
	{name: "steam_lid", type:"image", src: "data/img/sprite/area04/steam_lid.png"},
	{name: "kettle", type:"image", src: "data/img/sprite/area04/kettle.png"},
	{name: "oil_bottle2", type:"image", src: "data/img/sprite/area04/oil_bottle2.png"},
	{name: "knife_stand", type:"image", src: "data/img/sprite/area04/knife_stand.png"},
	{name: "pan_top1", type:"image", src: "data/img/sprite/area04/pan_top1.png"},
	{name: "pan_top2", type:"image", src: "data/img/sprite/area04/pan_top2.png"},
	{name: "popcorn", type:"image", src: "data/img/sprite/area04/popcorn.png"},
	{name: "toaster", type:"image", src: "data/img/sprite/area04/toaster.png"},
	{name: "wind", type:"image", src: "data/img/sprite/area04/wind.png"},
	{name: "window", type:"image", src: "data/img/sprite/area04/window.png"},
	{name: "airvent_button", type:"image", src: "data/img/sprite/area04/airvent_button.png"},
	//debug
	{name: "blank", type:"image", src: "data/img/sprite/debug/blank.png"},
	//{name: "onoffpallet", type:"image", src: "data/img/sprite/debug/onoffpallet.png"},
	//{name: "MultiStateEntityPallet", type:"image", src: "data/img/sprite/debug/MultiStateEntityPallet.png"},
	//{name: "switch", type:"image", src: "data/img/sprite/debug/switch.png"},
    
    // GUI images
	{name: "main_screen", type:"image", src: "data/img/backgrounds/main_screen.png"},
    {name: "pauseButton", type:"image", src: "data/img/gui/pauseButton.png"},
    {name: "pause_menu", type:"image", src: "data/img/gui/pause_menu.png"},
    {name: "restartButton", type:"image", src: "data/img/gui/restartButton.png"},
    {name: "backButton", type:"image", src: "data/img/gui/backButton.png"},
    {name: "menuButton", type:"image", src: "data/img/gui/menuButton.png"},
    {name: "levelButton", type:"image", src: "data/img/gui/levelButton.png"},
    {name: "playButton", type:"image", src: "data/img/gui/playButton.png"},
    {name: "instructionButton", type:"image", src: "data/img/gui/instructionButton.png"},
    {name: "chooseLevelBG", type:"image", src: "data/img/gui/chooseLevel.png"},
    {name: "chooseLevel1", type:"image", src: "data/img/gui/chooseLevel1.png"},
    {name: "chooseLevel2", type:"image", src: "data/img/gui/chooseLevel2.png"},
    {name: "chooseLevel3", type:"image", src: "data/img/gui/chooseLevel3.png"},
    {name: "chooseLevel4", type:"image", src: "data/img/gui/chooseLevel4.png"},
    {name: "clickEverywhere", type:"image", src: "data/img/gui/clickEverywhere.png"},
    {name: "continueButton", type:"image", src: "data/img/gui/continueButton.png"},
    
    // Game font
    //{name: "32x32_font",          type:"image", src: "data/img/font/32x32_font.png"},
	
	// Comic Strips
    {name: "comic_strip1", type:"image", src: "data/img/backgrounds/comic_strip1.png"},
    {name: "comic_strip2", type:"image", src: "data/img/backgrounds/comic_strip2.png"},
    {name: "comic_strip3", type:"image", src: "data/img/backgrounds/comic_strip3.png"},
    {name: "comic_strip4", type:"image", src: "data/img/backgrounds/comic_strip4.png"},
    {name: "comic_strip5", type:"image", src: "data/img/backgrounds/comic_strip5.png"},
    {name: "youwin", type:"image", src: "data/img/backgrounds/youwin.png"},
	
	// Maps: {name: "example01", type: "tmx", src: "data/map/example01.tmx"},
 	{name: "main_menu", type:"tmx", src:"data/map/main_menu.tmx"},
 	{name: "scene1", type:"tmx", src:"data/map/scene1.tmx"},
 	{name: "area01", type:"tmx", src:"data/map/area01.tmx"},
 	{name: "scene2", type:"tmx", src:"data/map/scene2.tmx"},
 	{name: "area02", type:"tmx", src:"data/map/area02.tmx"},
 	{name: "scene3", type:"tmx", src:"data/map/scene3.tmx"},
 	{name: "area03", type:"tmx", src:"data/map/area03.tmx"},
 	{name: "scene4", type:"tmx", src:"data/map/scene4.tmx"},
 	{name: "area04", type:"tmx", src:"data/map/area04.tmx"},
 	{name: "scene5", type:"tmx", src:"data/map/scene5.tmx"},
 	{name: "scene6", type:"tmx", src:"data/map/scene6.tmx"},
 	
	// Background music: {name: "example_bgm", type: "audio", src: "data/bgm/", channel : 1},
    {name: "melody", type: "audio", src: "data/bgm/", channel : 1},
    {name: "area01", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area03", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area02", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area04", type: "audio", src: "data/bgm/", channel : 1},
    
	// Sound effects: {name: "example_sfx", type: "audio", src: "data/sfx/", channel : 2}
    {name: "click", type: "audio", src: "data/sfx/", channel:1},
    {name: "woosh", type: "audio", src: "data/sfx/", channel:2},
    {name: "crack", type: "audio", src: "data/sfx/", channel:1},
    {name: "ice_break", type: "audio", src: "data/sfx/", channel:1},
    {name: "squelch", type: "audio", src: "data/sfx/", channel:1},
    {name: "clickeverywhere", type: "audio", src: "data/sfx/", channel:1},
    {name: "thud", type: "audio", src: "data/sfx/", channel:1},
    {name: "fridgeopen", type: "audio", src: "data/sfx/", channel:1},
    {name: "opencork", type: "audio", src: "data/sfx/", channel:1},
    {name: "cheesefall", type: "audio", src: "data/sfx/", channel:1},
    {name: "meatfalling", type: "audio", src: "data/sfx/", channel:1},
    {name: "booksfall2", type: "audio", src: "data/sfx/", channel:1},
    {name: "clink", type: "audio", src: "data/sfx/", channel:1},
    {name: "clink3", type: "audio", src: "data/sfx/", channel:1},
    {name: "boing", type: "audio", src: "data/sfx/", channel:1},
    {name: "hulksmash", type: "audio", src: "data/sfx/", channel:1},
    {name: "toiletroll", type: "audio", src: "data/sfx/", channel:1},
    {name: "watersplash", type: "audio", src: "data/sfx/", channel:1},
    {name: "watersplash", type: "audio", src: "data/sfx/", channel:1},
    {name: "rattle", type: "audio", src: "data/sfx/", channel:1},
    {name: "spongeplop", type: "audio", src: "data/sfx/", channel:1},
    {name: "window_squeak", type: "audio", src: "data/sfx/", channel:1},
    {name: "onstove", type: "audio", src: "data/sfx/", channel:1},
    {name: "waterfilling", type: "audio", src: "data/sfx/", channel:1},
    {name: "waterdrain", type: "audio", src: "data/sfx/", channel:1},
    {name: "drainwater", type: "audio", src: "data/sfx/", channel:1},
    {name: "clunk", type: "audio", src: "data/sfx/", channel:1},
    {name: "liquidshake", type: "audio", src: "data/sfx/", channel:1},
    {name: "ticktock", type: "audio", src: "data/sfx/", channel:1},
    {name: "canshake", type: "audio", src: "data/sfx/", channel:1},
    {name: "canshake2", type: "audio", src: "data/sfx/", channel:1},
    {name: "squeakyvalve", type: "audio", src: "data/sfx/", channel:1},
    {name: "metalstuck", type: "audio", src: "data/sfx/", channel:1},
    {name: "squish", type: "audio", src: "data/sfx/", channel:1},
    {name: "mouse", type: "audio", src: "data/sfx/", channel:1},
    {name: "anishing", type: "audio", src: "data/sfx/", channel:1},
    {name: "suction", type: "audio", src: "data/sfx/", channel:1},
    {name: "popcorn", type: "audio", src: "data/sfx/", channel:1},
    {name: "spongeplop", type: "audio", src: "data/sfx/", channel:1},
    {name: "squeak", type: "audio", src: "data/sfx/", channel:1},
    {name: "keyrattle", type: "audio", src: "data/sfx/", channel:1},
    {name: "panslide", type: "audio", src: "data/sfx/", channel:1},
    {name: "toaster", type: "audio", src: "data/sfx/", channel:1},
    {name: "whimper", type: "audio", src: "data/sfx/", channel:1},
    {name: "step3", type: "audio", src: "data/sfx/", channel:1}
    
    // Atlases {name: "example_tps", type: "tps", src: "data/img/example_tps.json"}
];
